name: master_deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Packages
      run: npm install
    - name: Deploy to GH Pages
      run:
        git config --global user.name $user_name
        git config --global user.email $user_email
        git remote set-url origin https://${github_token}@github.com/${repository}
        npm run deploy
      env:
        user_name: 'ivorgreen'
        user_email: 'ivorrgreen1@gmail.com'
        github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    repository: ${{ github.repository }}
        npm run deploy
    - name: Updating Domain
      run: echo "Update domain"
